#!bin/bash
#script para instalação e preparação de recusos basicos para utilização do sistema

#Sistema Operacional: Deepin, Debian(Strech, main e contrib)

echo "iniciando processos de configuração"

echo "Favor, não cancele ou feche essa janela"

echo "Digite a senha do super usuário"

#removendo travas de utilização do sistema
sudo rm /var/lib/dpkg/lock-frontend ; sudo rm /var/cache/apt/archives/lock ;

#pasta auxiliar temporaria
mkdir /home/$USER/Desktop/temp
cd /home/$USER/Desktop/temp

#atualização do sistema para reparar pacotes
sudo apt update

sudo apt upgrade

sudo apt autoremove

#Atualização do source.list
sudo rm /etc/apt/sources.list
sudo echo \
"## Generated by deepin-installer
deb [by-hash=force] http://packages.deepin.com/deepin lion main contrib non-free
deb-src http://packages.deepin.com/deepin lion main contrib non-free

#### REPOSITORIOS DEBIAN STRETCH \"deb.debian.org\"

###Repositorio Base ###

deb http://deb.debian.org/debian/ stretch main contrib non-free
deb-src http://deb.debian.org/debian/ stretch main contrib non-free

###Repositorio security.debian.org/ ###

deb http://deb.debian.org/debian-security/ stretch/updates main contrib non-free
deb-src http://deb.debian.org/debian-security/ stretch/updates main contrib non-free

###Repositorio stretch-updates ###

deb http://deb.debian.org/debian/ stretch-updates main contrib non-free
deb-src http://deb.debian.org/debian/ stretch-updates main contrib non-free

###Repositorio (stretch) stretch-backports ###

deb http://deb.debian.org/debian/ stretch-backports main contrib non-free
deb-src http://deb.debian.org/debian/ stretch-backports main contrib non-free


" >> sources.list

sudo mv sources.list /etc/apt/


sudo apt update

sudo apt upgrade

sudo apt autoremove

reboot
