#script para instalação e preparação de recusos basicos para utilização do sistema

#Sistema Operacional: Deepin, Debian(Strech, main e contrib)

echo "iniciando processos de configuração"

echo "Favor, não cancele ou feche essa janela"

echo "Digite a senha do super usuário"

#removendo travas de utilização do sistema
sudo rm /var/lib/dpkg/lock-frontend ; sudo rm /var/cache/apt/archives/lock ;

#pasta auxiliar temporaria
mkdir /home/$USER/Desktop/temp
cd /home/$USER/Desktop/temp

#atualização do sistema para reparar pacotes
sudo apt update

sudo apt upgrade

sudo apt autoremove

#Atualização do source.list
sudo rm /etc/apt/sources.list
sudo echo \
"## Generated by deepin-installer
deb [by-hash=force] http://packages.deepin.com/deepin lion main contrib non-free
deb-src http://packages.deepin.com/deepin lion main contrib non-free

#### REPOSITORIOS DEBIAN STRETCH \"deb.debian.org\"

###Repositorio Base ###

deb http://deb.debian.org/debian/ stretch main contrib non-free
deb-src http://deb.debian.org/debian/ stretch main contrib non-free

###Repositorio security.debian.org/ ###

deb http://deb.debian.org/debian-security/ stretch/updates main contrib non-free
deb-src http://deb.debian.org/debian-security/ stretch/updates main contrib non-free

###Repositorio stretch-updates ###

deb http://deb.debian.org/debian/ stretch-updates main contrib non-free
deb-src http://deb.debian.org/debian/ stretch-updates main contrib non-free

###Repositorio (stretch) stretch-backports ###

deb http://deb.debian.org/debian/ stretch-backports main contrib non-free
deb-src http://deb.debian.org/debian/ stretch-backports main contrib non-free


" >> sources.list

sudo mv sources.list /etc/apt/


sudo apt update

sudo apt upgrade

sudo apt autoremove

#instalação de programas padrão

sudo apt-get install wget transmission zsh git curl openjdk-11-jdk-headless openjdk-11-source openjdk-11-dbg openjdk-11-doc openjfx maven sl logisim vsftpd g++ code



#Download e instalação das ides

wget -c https://download-cf.jetbrains.com/python/pycharm-professional-2019.3.tar.gz

wget -c https://download-cf.jetbrains.com/idea/ideaIU-2019.3.tar.gz

wget -c https://download-cf.jetbrains.com/cpp/CLion-2019.3.1.tar.gz

wget -c https://download.virtualbox.org/virtualbox/6.0.14/virtualbox-6.0_6.0.14-133895~Debian~stretch_amd64.deb

wget -c https://dl.discordapp.net/apps/linux/0.0.9/discord-0.0.9.deb


sudo tar -xzvf CLion-2019.3.1.tar.gz -C /home/$USER/

sudo tar -xzvf ideaIU-2019.3.tar.gz -C /home/$USER/

sudo tar -xzvf pycharm-professional-2019.3.tar.gz -C /home/$USER/


sudo dpkg -i discord-0.0.9.deb

sudo dpkg -i virtualbox-6.0_6.0.14-133895~Debian~stretch_amd64.deb


#remoção da pasta temporaria
cd ..

sudo rm -r temp

cd

mv clion-* clion

mv idea-* idea

mv pycharm-* pycharm

#Download e instalação do oh my zsh


sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
